jQuery1830656767985077358_1528891062984({
     "conf":{
        'urlhash': '2e7a6479da180b322d581031997036ef',
        'layout':'_51cto',
        'islogin': '0', 
		'home':'',
        'loginuid': '', 
		'uid': '', 
        'uname': '',  
        'uface': '',  
        'colortype': '',  
        'color': '',  
        'txtsize': '300',   
        'duface': '/static/images/duface.png',
        'domain': '51cto.com',
        'artinfo_id': '377464',
        'aid':'544957',
        'title': 'Docker Compose：链接外部容器的几种方式',
		'url': 'http://cloud.51cto.com/art/201707/544957.htm',
        'col_id': '15',
        'comment_count': '0',
        'zan_count': '0',
        'share_count': '0',
        'login': false,  
        'dswidth': '400', 
        'dsheight': '400', 
        'dslogin': 'http://127.0.0.1/?page_id=9',
        'cmttit': '互动评论<div style="clear: both;"></div>',
        'txtsize': '300',
        //'uacns': '0条评论', 
        'uvons': '0次被喜欢',        
		'fc_pagesize':'10',
		'fr_pagesize':'2',
		'login_url': 'http://home.51cto.com/index.php?s=/Index/index/reback/http%253A%252F%252Fcloud.51cto.com%252Fart%252F201707%252F544957.htm',
		'reg_url':'http://home.51cto.com/user/register?reback=http%253A%252F%252Fcloud.51cto.com%252Fart%252F201707%252F544957.htm',
	'isforbid':'1',
    },
    "lang" :{
		'shareSina1': '#51CTO评论#',
		'shareSina2': '...【',
		'shareSina3': '】@51cto官方微博',
		'boxTitle': '内容点评',
		'boxNumStr1': '已有',
		'boxNumStr2': '条评论',
		'boxZan': '次赞',
		'boxTishi1': '还可以输入',
		'boxTishi2': '字',
		'boxSubmit': '提交',
		'userStr1': '欢迎您！',
		'userStr2': '您还没有登录！',
		'userStr3': '请先',
		'userStr4': '登录',
		'userStr5': '或',
		'userStr6': '注册',
		'userStr7': '正在加载数据中...',
		'userStr8': '更多',
		'userStr9': '发表于:',
        'iptCmt': '请输入你的评论',
        'iptUname': '昵称（必填）',
        'iptEmail': '邮箱',
        'iptUlink': '网址',
        'sending': '发布中',
        'noCmt': '还没有评论内容',
        'sendSucc': '发布成功',
        'hotSort': '按热度排序',
        'timeSort': '按时间排序',
        'emailErr': '邮箱格式不正确',
        'unameEpy': '昵称不能为空',
        'unameErr': '请先登陆',
        'ulinkErr': '网址格式不正确',
        'emailEpy': '邮箱不能为空',
        'loadRpy': '加载回复中...',
        'loadCmt': '加载评论中...',
        'loadData': '正在加载数据中...',
        'loadHold': '还没响应，看来没HOLD住 !',
        'addCmt': '发&nbsp;&nbsp;布',
        'addRpy': '回&nbsp;&nbsp;复',
        'spamWarn': '信息发布失败',
        'againWarn': '请不要发布重复信息',
        'shortWarn': '发表得太频繁了',
        'ttsWarn': '超出字符限制了',
        'mCmtS': '查看更多评论',
        'mRpyS': '查看更多回复',
        'cmtS': '评论',
        'rpyS': '回复',
		'cmtShare': '分享',
        'dS': '顶',
        'traS': '转发',
        'delS': '删除',
        'rsrS': '恢复',
        'viyS': '通过',
        'bckS': '加入黑名单',
        'topS': '置顶',
        'dopS': '取消置顶',
        'font': "''Microsoft YaHei',arial,tahoma,宋体,sans-serif",
        'use': '用',
        'account': '账号登陆',
        'tsina': '新浪微博',
        'tqq': '腾讯微博',
        'renren': '人人网',
        'qq': 'QQ',
        't163': '网易微博',
        'tsohu': '搜狐微博',
        'kaixin001': '开心网',
        'msn': 'MSN',
        'douban': '豆瓣网',
        'facebook': 'Facebook',
        'twitter': 'Twitter',
	    'forbidden_comment': '您已被禁止评论',
	}
 });
