version: '2'
services:
  gateway:
     image: "192.168.42.162:5000/gateway:1.0-SNAPSHOT"
     hostname: gateway
     ports:
       - "8080:8080"
     networks:
       - app_net
     environment:
       - server_port=8080
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  idservice:
     image: "192.168.42.162:5000/idservice:1.0-SNAPSHOT"
     hostname: idservice
     ports:
       - "9999:9999"
     networks:
       - app_net
     environment:
       - server_port=9999
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  menuoperateservice:
     image: "192.168.42.162:5000/menuoperateservice:1.0-SNAPSHOT"
     hostname: menuoperateservice
     ports:
       - "6681:6681"
     networks:
       - app_net
     environment:
       - server_port=6681
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  roleoperateservice:
     image: "192.168.42.162:5000/roleoperateservice:1.0-SNAPSHOT"
     hostname: roleoperateservice
     ports:
       - "6731:6731"
     networks:
       - app_net
     environment:
       - server_port=6731
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  roleservice:
     image: "192.168.42.162:5000/roleservice:1.0-SNAPSHOT"
     hostname: roleservice
     ports:
       - "6691:6691"
     networks:
       - app_net
     environment:
       - server_port=6691
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  userservice:
     image: "192.168.42.162:5000/userservice:1.0-SNAPSHOT"
     hostname: userservice
     ports:
       - "6671:6671"
     networks:
       - app_net
     environment:
       - server_port=6671
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  useroperateservice:
     image: "192.168.42.162:5000/useroperateservice:1.0-SNAPSHOT"
     hostname: useroperateservice
     ports:
       - "6701:6701"
     networks:
       - app_net
     environment:
       - server_port=6701
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  userroleservice:
     image: "192.168.42.162:5000/userroleservice:1.0-SNAPSHOT"
     hostname: userroleservice
     ports:
       - "6721:6721"
     networks:
       - app_net
     environment:
       - server_port=6721
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  zipkin:
     image: "192.168.42.162:5000/zipkin:1.0-SNAPSHOT"
     hostname: zipkin
     ports:
       - "9411:9411"
     networks:
       - app_net
     environment:
       - server_port=9411
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/

networks:
  app_net:
    external: true
#说明： app_net是手动创建的一个公用的外部网络，执行命令：docker network create app_net
#       external: true 表示该创建的网络不是由docker-compose up 执行的时候自动创建的，是手动创建的，那么在执行docker-compose down的时候该网络不会被自动删除
#       不同的docker-compose.yml 创建的容器之间是不能通信的，实际中经常需要通信，为了达到这一目的就需要创建一个公用网络，然后不同docker-compose.yml产生的容
#       都连上这个公共网络，那么就可以实现它们的通信了。