version: '2'
services:
  gateway:
     image: "gateway:1.0-SNAPSHOT"
     hostname: gateway
     ports:
       - "8080:8080"
     networks:
       - app_net
     environment:
       - server_port=8080
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  hellocontroller:
     image: "hellocontroller:1.0-SNAPSHOT"
     hostname: hellocontroller
     ports:
       - "6661:6661"
     networks:
       - app_net
     environment:
       - server_port=6661
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  helloservice:
     image: "helloservice:1.0-SNAPSHOT"
     hostname: helloservice
     ports:
       - "6671:6671"
     networks:
       - app_net
     environment:
       - server_port=6671
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
  zipkin:
     image: "zipkin:1.0-SNAPSHOT"
     hostname: zipkin
     ports:
       - "9411:9411"
     networks:
       - app_net
     environment:
       - server_port=9411
       - eureka_client_service-url_defaultZone=http://eureka1:1111/eureka/,http://eureka2:1112/eureka/

networks:
  app_net:
    external: true
